version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=201210'
      - 'POSTGRES_DB=postgres'

  app:
    build: ./
    container_name: 'SpringApi'
    ports:
      - 8080:8080
